spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/makeboluo000/conifg-repo
          username: makeboluo000@163.com
          password: make2828378
          basedir: D:\\java_idea\\sc_config\\basedir #远程配置文件拉取下来的存放路径1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka/